[pytest]
testpaths = tests
pythonpath = . plugins
addopts = --tb=short -q
env =
    _AIRFLOW__AS_LIBRARY=1
    AIRFLOW_HOME=/tmp/airflow
    AIRFLOW__CORE__UNIT_TEST_MODE=True
    AIRFLOW__CORE__LOAD_EXAMPLES=False
